version: '3'

services:
    web-node-js:
        image: shissanupong/demo-nodejs:latest
        ports:
            - "3000:3000"
        restart: always
        environment:
            - MONGODB_ADDON_URI=mongodb://mongodb:27017/test
    mongodb:
        image: mongo:latest
        ports: 
            - "27017:27017"
        
